### ISSUE TITLE
Error: stat ./get-last-updated.go: no such file or directory

### ISSUE THREAD

**Issue by Borda** [jamesmortensen/cache-container-images-action#2]
It seems like the action does not properly fetch all files from the repo; it complains about

```
Home =  /home/runner
PWD =  /home/runner/work/grid/grid
CONTAINER_IMAGES=cypress/included:12.17.1
rm: cannot remove 'container-images-key.txt': No such file or directory
Images URIS=cypress/included/tags/12.17.1
cypress/included/tags/12.17.1
Checking last updated time for https://hub.docker.com/v2/repositories/cypress/included/tags/12.17.1/
Error: stat ./get-last-updated.go: no such file or directory
```

For reproducing, this is the workflow's step:

```yaml
    - name: Cache Container Images
      uses: jamesmortensen/cache-container-images-action@de9e1ef6907f913f2a7a3deb47109eaf9fb2865f  # v1
      with:
        prefix-key: 'cypress-included'
        images: |
          cypress/included:12.17.1
```

cc: @jamesmortensen
